# Generated by Django 4.0 on 2021-12-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(max_length=7)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
